### ISSUE TITLE
Hi, Today i tried to update my Coin metadata but i got a error

### ISSUE THREAD

**Issue by elogt-crypto** [mofrey-max/token-metadata-program#3]
Here is the error code

`` ubuntu@21.125.645.20:~/Documents/token-git/token-metadata-program/mpl$ ts-node intial.ts
/usr/local/lib/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
intial.ts:48:71 - error TS2345: Argument of type '{ createMetadataAccountArgsV2: { data: { name: string; symbol: string; uri: string; sellerFeeBasisPoints: number; creators: null; collection: null; uses: null; }; isMutable: boolean; }; }' is not assignable to parameter of type 'PublicKey'.
  Type '{ createMetadataAccountArgsV2: { data: { name: string; symbol: string; uri: string; sellerFeeBasisPoints: number; creators: null; collection: null; uses: null; }; isMutable: boolean; }; }' is missing the following properties from type 'PublicKey': equals, toBase58, toJSON, toBytes, and 3 more.

48     const ix = mpl.createCreateMetadataAccountV2Instruction(accounts, args);
                                                                         ~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  diagnosticCodes: [ 2345 ]
} ``

i hope you fix this soon

**Comment by mofrey-max** [comment]
Sorry for not answering your question on time i will make my email public for fast response. improper configuration of Keypair may result to error. If your still on the issue kindly reach on this email manugodfrey8@gmail.com

**Comment by mofrey-max** [comment]
From the error above recheck your public to be sure is the right Publickey
